#!/bin/bash
# forge-repomap.sh — Generate a repository map for Forge orientation
# Usage: ./forge-repomap.sh [target-dir]
# Output: <target-dir>/research/repo-map.md

set -e

TARGET="${1:-.}"
OUTDIR="$TARGET/research"
OUTFILE="$OUTDIR/repo-map.md"

if [ ! -d "$TARGET" ]; then
    echo "Error: directory '$TARGET' not found"
    exit 1
fi

mkdir -p "$OUTDIR"

echo "Generating repo map for: $TARGET"

cat > "$OUTFILE" << 'HEADER'
# Repository Map

*Auto-generated by forge-repomap.sh*

HEADER

# File stats
echo "## Stats" >> "$OUTFILE"
echo "" >> "$OUTFILE"
if command -v find &>/dev/null; then
    total_files=$(find "$TARGET" -type f -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/__pycache__/*' -not -path '*/.venv/*' -not -path '*/venv/*' -not -path '*/.env/*' 2>/dev/null | wc -l | tr -d ' ')
    echo "- **Total files**: $total_files" >> "$OUTFILE"

    # Count by extension
    echo "- **By type**:" >> "$OUTFILE"
    find "$TARGET" -type f -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/__pycache__/*' -not -path '*/.venv/*' -not -path '*/venv/*' -not -path '*/.env/*' 2>/dev/null \
        | sed 's/.*\.//' | sort | uniq -c | sort -rn | head -10 \
        | while read count ext; do
            echo "  - .$ext: $count" >> "$OUTFILE"
        done
fi
echo "" >> "$OUTFILE"

# Directory structure (max depth 3)
echo "## Directory Structure" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo '```' >> "$OUTFILE"
find "$TARGET" -type d -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/__pycache__/*' -not -path '*/.venv/*' -maxdepth 3 2>/dev/null \
    | sort | head -50 >> "$OUTFILE"
echo '```' >> "$OUTFILE"
echo "" >> "$OUTFILE"

# Key files
echo "## Key Files" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "### Config & Entry Points" >> "$OUTFILE"
for f in package.json pyproject.toml Cargo.toml go.mod setup.py setup.cfg Makefile Dockerfile docker-compose.yml; do
    if [ -f "$TARGET/$f" ]; then
        echo "- \`$f\`" >> "$OUTFILE"
    fi
done
echo "" >> "$OUTFILE"

echo "### Documentation" >> "$OUTFILE"
for f in README.md CLAUDE.md CONTRIBUTING.md CHANGELOG.md; do
    if [ -f "$TARGET/$f" ]; then
        echo "- \`$f\`" >> "$OUTFILE"
    fi
done
echo "" >> "$OUTFILE"

# Source files by size (top 10 largest)
echo "### Largest Source Files" >> "$OUTFILE"
echo "" >> "$OUTFILE"
find "$TARGET" -type f \( -name '*.py' -o -name '*.js' -o -name '*.ts' -o -name '*.go' -o -name '*.rs' -o -name '*.java' -o -name '*.rb' \) \
    -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/__pycache__/*' 2>/dev/null \
    | xargs wc -l 2>/dev/null | sort -rn | head -11 | tail -10 \
    | while read lines file; do
        echo "- \`$file\` ($lines lines)" >> "$OUTFILE"
    done
echo "" >> "$OUTFILE"

# Tests
echo "### Test Files" >> "$OUTFILE"
find "$TARGET" -type f \( -name 'test_*' -o -name '*_test.*' -o -name '*.test.*' -o -name '*.spec.*' \) \
    -not -path '*/.git/*' -not -path '*/node_modules/*' 2>/dev/null \
    | head -20 \
    | while read f; do
        echo "- \`$f\`" >> "$OUTFILE"
    done
echo "" >> "$OUTFILE"

echo "Done: $OUTFILE"
